In [35]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [36]:
df=pd.read_csv('heart.csv')
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [38]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [39]:
df.describe(include='all')

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
count,918.000000,918,918,918.000000,918.000000,918.000000,918,918.000000,918,918.000000,918,918.000000
unique,NaN,2,4,NaN,NaN,NaN,3,NaN,2,NaN,3,NaN
top,NaN,M,ASY,NaN,NaN,NaN,Normal,NaN,N,NaN,Flat,NaN
freq,NaN,725,496,NaN,NaN,NaN,552,NaN,547,NaN,460,NaN
mean,53.510893,NaN,NaN,132.396514,198.799564,0.233115,NaN,136.809368,NaN,0.887364,NaN,0.553377
std,9.432617,NaN,NaN,18.514154,109.384145,0.423046,NaN,25.460334,NaN,1.066570,NaN,0.497414
min,28.000000,NaN,NaN,0.000000,0.000000,0.000000,NaN,60.000000,NaN,-2.600000,NaN,0.000000
25%,47.000000,NaN,NaN,120.000000,173.250000,0.000000,NaN,120.000000,NaN,0.000000,NaN,0.000000
50%,54.000000,NaN,NaN,130.000000,223.000000,0.000000,NaN,138.000000,NaN,0.600000,NaN,1.000000
75%,60.000000,NaN,NaN,140.000000,267.000000,0.000000,NaN,156.000000,NaN,1.500000,NaN,1.000000
max,77.000000,NaN,NaN,200.000000,603.000000,1.000000,NaN,202.000000,NaN,6.200000,NaN,1.000000

In [40]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [41]:
df.duplicated().sum()

np.int64(0)

In [42]:
df.nunique()

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

CONVERTING CATEGORICAL VARIABLE TO NUMERIC
- Sex:M:1,F:0
- ChestPainType : ATA=0,NAP=1,ASY=2,TA=3
- RestingECG :Normal=0,ST=1,LVH=2
- ExerciseAngina :N=0,Y=1
- ST_Slope :Up=0,Flat=1,Down=2

In [43]:
df['Sex']=df['Sex'].map({'M':1,'F':0})
df['ChestPainType']=df['ChestPainType'].map({'ATA':0,'NAP':1,'ASY':2,'TA':3})
df['RestingECG']=df['RestingECG'].map({'Normal':0,'ST':1,'LVH':2})
df['ExerciseAngina']=df['ExerciseAngina'].map({'N':0,'Y':1})
df['ST_Slope']=df['ST_Slope'].map({'Up':0,'Flat':1,'Down':2})

In [44]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,0,140,289,0,0,172,0,0.0,0,0
1,49,0,1,160,180,0,0,156,0,1.0,1,1
2,37,1,0,130,283,0,1,98,0,0.0,0,0
3,48,0,2,138,214,0,0,108,1,1.5,1,1
4,54,1,1,150,195,0,0,122,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,0,132,0,1.2,1,1
914,68,1,2,144,193,1,0,141,0,3.4,1,1
915,57,1,2,130,131,0,0,115,1,1.2,1,1
916,57,0,0,130,236,0,2,174,0,0.0,1,1
917,38,1,1,138,175,0,0,173,0,0.0,0,0

In [45]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [46]:
df['Cholesterol'].value_counts()

Cholesterol
0      172
254     11
220     10
223     10
204      9
      ...
353      1
278      1
157      1
176      1
131      1
Name: count, Length: 222, dtype: int64

use knn imputer dataset me kuch values missing hoti hai unhe fill karna padta hai imputer se jo ki nearest neabours se estimate karta hai

In [47]:
import numpy as np

# Float 0.0 ko NaN banao
df['Cholesterol'] = df['Cholesterol'].apply(
    lambda x: np.nan if x == 0.0 else x
)

# Check karo
print(df['Cholesterol'].isna().sum())  # 172 aana chahiye ✅

# Ab KNN Imputer lagao
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(df)
df = pd.DataFrame(after_impute, columns=df.columns)

# Verify karo
count = 0
for i in df['Cholesterol']:
    if i == 0.0:
        count += 1
print(count)  # 0 aana chahiye

172
0

In [48]:
df['RestingBP'][df['RestingBP']==0]

449    0.0
Name: RestingBP, dtype: float64

In [49]:
# Float 0.0 ko NaN banao
df['RestingBP'] = df['RestingBP'].apply(
    lambda x: np.nan if x == 0.0 else x
)

# Check karo
print(df['RestingBP'].isna().sum())  # 1 aana chahiye ✅

# Ab KNN Imputer lagao
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(df)
df = pd.DataFrame(after_impute, columns=df.columns)

# Verify karo
count = 0
for i in df['RestingBP']:
    if i == 0.0:
        count += 1
print(count)  # 0 aana chahiye

1
0

In [50]:
df['RestingBP'].unique()

array([140., 160., 130., 138., 150., 120., 110., 136., 115., 100., 124.,
       113., 125., 145., 112., 132., 118., 170., 142., 190., 135., 180.,
       108., 155., 128., 106.,  92., 200., 122.,  98., 105., 133.,  95.,
        80., 137., 185., 165., 126., 152., 116., 144., 154., 134., 104.,
       139., 131., 141., 178., 146., 158., 123., 102.,  96., 143., 172.,
       156., 114., 127., 101., 174.,  94., 148., 117., 192., 129., 164.])

In [51]:
df['RestingBP'].isnull().sum()

np.int64(0)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    float64
 1   Sex             918 non-null    float64
 2   ChestPainType   918 non-null    float64
 3   RestingBP       918 non-null    float64
 4   Cholesterol     918 non-null    float64
 5   FastingBS       918 non-null    float64
 6   RestingECG      918 non-null    float64
 7   MaxHR           918 non-null    float64
 8   ExerciseAngina  918 non-null    float64
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    float64
 11  HeartDisease    918 non-null    float64
dtypes: float64(12)
memory usage: 86.2 KB

In [53]:
withoutold=df.columns
withoutold=withoutold.drop('Oldpeak')
df[withoutold]=df[withoutold].astype('int32')

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int32
 1   Sex             918 non-null    int32
 2   ChestPainType   918 non-null    int32
 3   RestingBP       918 non-null    int32
 4   Cholesterol     918 non-null    int32
 5   FastingBS       918 non-null    int32
 6   RestingECG      918 non-null    int32
 7   MaxHR           918 non-null    int32
 8   ExerciseAngina  918 non-null    int32
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    int32
 11  HeartDisease    918 non-null    int32
dtypes: float64(1), int32(11)
memory usage: 46.7 KB

In [55]:
df.corr()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
Age,1.000000,0.055750,0.214164,0.263128,0.057108,0.198039,0.213152,-0.382045,0.215793,0.258612,0.268264,0.282039
Sex,0.055750,1.000000,0.179766,0.009658,-0.080395,0.120076,-0.018343,-0.189186,0.190664,0.105734,0.150693,0.305445
ChestPainType,0.214164,0.179766,1.000000,0.073016,0.038855,0.155111,0.112067,-0.273076,0.324049,0.300846,0.352364,0.459017
RestingBP,0.263128,0.009658,0.073016,1.000000,0.113194,0.067556,0.094144,-0.109329,0.152621,0.174464,0.082401,0.118333
Cholesterol,0.057108,-0.080395,0.038855,0.113194,1.000000,0.058798,0.074925,-0.028855,0.083761,0.065988,0.071345,0.101263
FastingBS,0.198039,0.120076,0.155111,0.067556,0.058798,1.000000,0.050707,-0.131438,0.060451,0.052698,0.175774,0.267291
RestingECG,0.213152,-0.018343,0.112067,0.094144,0.074925,0.050707,1.000000,0.048552,0.036119,0.114428,0.078807,0.061011
MaxHR,-0.382045,-0.189186,-0.273076,-0.109329,-0.028855,-0.131438,0.048552,1.000000,-0.370425,-0.160691,-0.343419,-0.400421
ExerciseAngina,0.215793,0.190664,0.324049,0.152621,0.083761,0.060451,0.036119,-0.370425,1.000000,0.408752,0.428706,0.494282
Oldpeak,0.258612,0.105734,0.300846,0.174464,0.065988,0.052698,0.114428,-0.160691,0.408752,1.000000,0.501921,0.403951
ST_Slope,0.268264,0.150693,0.352364,0.082401,0.071345,0.175774,0.078807,-0.343419,0.428706,0.501921,1.000000,0.558771
HeartDisease,0.282039,0.305445,0.459017,0.118333,0.101263,0.267291,0.061011,-0.400421,0.494282,0.403951,0.558771,1.000000

In [56]:
import plotly.express as px
px.line(df.corr()['HeartDisease'][:-1].sort_values())

Age and Heart disease distrbution

In [57]:
px.sunburst(df,path=['HeartDisease','Age'])

In [58]:
px.histogram(df,x='Age',color='HeartDisease')

In [59]:
px.pie(df,names='HeartDisease',title='Percentage of HeartDisease classes distribution')

In [60]:
px.histogram(df,x='Sex',color='HeartDisease')

In [61]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,0,140,289,0,0,172,0,0.0,0,0
1,49,0,1,160,180,0,0,156,0,1.0,1,1
2,37,1,0,130,283,0,1,98,0,0.0,0,0
3,48,0,2,138,214,0,0,108,1,1.5,1,1
4,54,1,1,150,195,0,0,122,0,0.0,0,0

In [62]:
X=df.drop('HeartDisease',axis=1)
y=df['HeartDisease']

In [63]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [64]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [65]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score
models=AdaBoostClassifier()
models.fit(X_train,y_train)
y_pre=models.predict(X_test)
print(accuracy_score(y_test,y_pre))

0.8586956521739131

In [66]:
from sklearn.svm import SVC
from sklearn.metrics import f1_score

kernels={'linear':0,'poly':0,'rbf':0,'sigmoid':0}
best=''

for i in kernels:
    svm=SVC(kernel=i)
    svm.fit(X_train,y_train)
    yhat=svm.predict(X_test)
    kernels[i]=f1_score(y_test,yhat,average='weighted')
    if kernels[i]==max(kernels.values()):
        best=i
    
svm=SVC(kernel=best)
svm.fit(X_train,y_train)
svm_pred=svm.predict(X_test)
print(f'SVM F1 Score ({best}): {f1_score(y_test,svm_pred,average='weighted')}')

SVM F1 Score (rbf): 0.8589349193327864

In [67]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
dtree=DecisionTreeClassifier(class_weight='balanced')
param_grid={
    'max_depth':[3,4,5,6,7,8],
    'min_samples_split':[2,3,4],
    'min_samples_leaf':[1,2,3,4],
    'random_state':[0,42]
}
grid_search=GridSearchCV(dtree,param_grid,cv=5)
grid_search.fit(X_train,y_train)
Ctree=DecisionTreeClassifier(**grid_search.best_params_,class_weight='balanced')
Ctree.fit(X_train,y_train)
dtc_pred=Ctree.predict(X_test)
print('DecisionTree Classifies :',accuracy_score(y_test,dtc_pred))

DecisionTree Classifies : 0.8369565217391305

In [68]:
# Add more models
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# Cross-validation
from sklearn.model_selection import cross_val_score
scores = cross_val_score(svm, X_train, y_train, cv=5)
print(f"CV Score: {scores.mean():.2f}")

CV Score: 0.86

In [69]:
import pickle
pickle.dump(svm,open('heart_model.pkl','wb'))
pickle.dump(scaler,open('heart_scaler.pkl','wb'))
print("SVM Model saved successfully !")

SVM Model saved successfully !